CREATE TABLE USERS (
  ID            INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME      VARCHAR(40),
  PASSWORD      VARCHAR(40),
  ROLE_ID       INT,
  REGISTER_TIME DATETIME DEFAULT current_timestamp NOT NULL
);


CREATE TABLE ROLES (
  ID   INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(40)
);


CREATE TABLE LOBTEST (
  ID           INT PRIMARY KEY AUTO_INCREMENT,
  BLOB_CONTENT BLOB,
  CLOB_CONTENT LONGTEXT
);
